language: 
    - python

python: 
    - "3.7"

services:
    - docker

before_script:
    - pip install docker-compose

script:
    - docker-compose run web flake8
    - docker-compose run web coverage run manage.py collectstatic --noinput --settings=settings.test
    - docker-compose run web coverage run manage.py test --settings=settings.test

after_success:
    - docker-compose run web codecov --token=${CODECOV_TOKEN}