language: 
    - python

python: 
    - "3.7"

services:
    - docker

before_script:
    - pip install docker-compose

script:
    - docker-compose run web python manage.py test --settings=settings.test && flake8