version: '3.7'

services:
    db:
        image: "postgres:11"
        environment: 
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    web:
        build: .
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - STRIPE_TEST_PUBLISHABLE_KEY=${STRIPE_TEST_PUBLISHABLE}
            - STRIPE_TEST_SECRET_KEY=${STRIPE_TEST_SECRET}
            - USE_S3=${USE_S3}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
        command: gunicorn petstore.wsgi -b 0.0.0.0:8000 
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on: 
            - db
    

volumes:
    postgres_data: