# Generated by Django 2.2.12 on 2020-04-19 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Payment received'), (3, 'In progress'), (4, 'Complete')], default=1)),
                ('billing_name', models.CharField(max_length=100, null=True)),
                ('billing_address', models.CharField(max_length=255, null=True)),
                ('billing_city', models.CharField(max_length=50, null=True)),
                ('billing_country', models.CharField(max_length=100, null=True)),
                ('billing_post_code', models.CharField(max_length=30, null=True)),
                ('shipping_name', models.CharField(max_length=100, null=True)),
                ('shipping_address', models.CharField(max_length=255, null=True)),
                ('shipping_city', models.CharField(max_length=50, null=True)),
                ('shipping_country', models.CharField(max_length=100, null=True)),
                ('shipping_post_code', models.CharField(max_length=30, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Item picked'), (4, 'Shipped'), (5, 'Cancelled')], default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_updated', models.DateField(auto_now=True)),
                ('dated_added', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
