# Generated by Django 2.2.12 on 2020-04-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_post_code',
            field=models.CharField(max_length=30, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_post_code',
            field=models.CharField(max_length=30, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
    ]
