# Generated by Django 2.2.12 on 2020-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Payment received'), (3, 'Order being picked'), (4, 'Complete')], default=1),
        ),
    ]
