# Generated by Django 2.2.11 on 2020-03-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
